version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/flask-fool
    steps:
      - checkout
      - restore_cache:
          keys:
          - build-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          - build-dependencies-{{ checksum "requirements.txt" }}-
          - build-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - save_cache:
          paths:
            - ./venv
          key: build-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/
  deploy:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/flask-fool
    steps:
      - checkout
      - restore_cache:
          keys:
          - deploy-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          - deploy-dependencies-{{ checksum "requirements.txt" }}-
          - deploy-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - save_cache:
          paths:
            - ./venv
          key: deploy-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: check version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: create pypirc
          command: |
            echo -e "[distutils]" > ~/.pypirc
            echo -e "index-servers=" >> ~/.pypirc
            echo -e " pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://upload.pypi.org/legacy" >> ~/.pypirc
            echo -e "username=$PYPI_USERNAME" >> ~/.pypirc
            echo -e "password=$PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload
          command: |
            . venv/bin/activate
            python setup.py sdist upload -r pypi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/